// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KV_SESSION_MAIN: KVNamespace;
	KV_SESSION_AUTH: KVNamespace;
	WHICH_ENV: "development";
	BACKEND_URL: "https://alleys-be.dmg04158.workers.dev";
	EMAIL_FROM_ADDR: "DoNotReply@alleys.app";
	EMAIL_CODE_LEN: 6;
	TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
	TURNSTILE_ENDPOINT: "https://challenges.cloudflare.com/turnstile/v0/siteverify";
	DATABASE_URL: string;
	EMAIL_CONN_STR: string;
	TURNSTILE_SECRET_KEY: string;
	HYPERDRIVE: Hyperdrive;
}
