// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	WHICH_ENV: "development";
	REDIRECT: "https://www.alleys.app";
	IMAGE_BUCKET_URL: "https://r2.alleys.app";
}
