// Generated by Wrangler on Sat Dec 07 2024 13:29:12 GMT+0900 (Korean Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	MY_KV: KVNamespace;
	WHICH_ENV: "development";
	TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
	TURNSTILE_ENDPOINT: "https://challenges.cloudflare.com/turnstile/v0/siteverify";
	DATABASE_URL: string;
	EMAIL_CONN_STR: string;
	TURNSTILE_SECRET_KEY: string;
	MY_BUCKET: R2Bucket;
	MY_DB: D1Database;
}
