name: Deploy Root

on:
  push:
    branches:
      - main
    paths:
      - "root/**"
      - ".github/workflows/deploy-root.yml"

  pull_request:
    branches:
      - main
    paths:
      - "root/**"
      - ".github/workflows/deploy-root.yml"
  
  repository_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check STOP_DEPLOY
        run: |
          if [ "${{ vars.STOP_DEPLOY }}" == "true" ]; then
            echo "Stopping job"
            exit 0
          fi
          echo "Continuing..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "./root"
          command: deploy --minify
          environment: production
        #   secrets:
        # env: